# AUTO-GENERATED BY INSTALLER
PROJECT_TITLE = "Intrusion Detection in WiFi 7 IoT Networks using Edge AI"
CUSTOM_ALGOS = ["RandomForest"",""Autoncoder"",""LSTM"]
COPYRIGHT_TEXT = "© Copyright: Dr Subar - FIST MMU Melaka Dec 2025"
